admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_time_in:
    path:     /admin/time_in/{id}
    defaults: { _controller: AdminBundle:Default:timeIn }

admin_time_in_no_params:
    path:     /admin/time_in/
    defaults: { _controller: AdminBundle:Default:timeIn }